### ISSUE TITLE
Plugin fails to load all of a sudden as of yesterday it seems

### ISSUE THREAD

**Issue by zbee** [awgil/ffxiv_visland#39]
I just noticed this morning that visland was not loading.

<details><summary>This was my issue loading the plugin:</summary>

```
10:43:27.493 ERR | [LOCALPLUGIN] Error while loading V(ery) Island
10:43:27.493 ERR | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
10:43:27.493 ERR |  ---> System.NullReferenceException: Object reference not set to an instance of an object.
10:43:27.493 ERR |    at FFXIVClientStructs.Interop.Resolver.ResolveFromCache() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 151
10:43:27.493 ERR |    at FFXIVClientStructs.Interop.Resolver.Resolve() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 171
10:43:27.493 ERR |    at visland.Plugin..ctor(DalamudPluginInterface dalamud) in /home/runner/work/ffxiv_visland/ffxiv_visland/ffxiv_visland/Plugin.cs:line 71
10:43:27.493 ERR |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
10:43:27.493 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
10:43:27.493 ERR |    --- End of inner exception stack trace ---
10:43:27.493 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
10:43:27.493 ERR |    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
10:43:27.493 ERR |    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 146
10:43:27.493 ERR |    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 454
10:43:27.510 ERR | [PLUGINW] Plugin installer threw an unexpected error
10:43:27.510 ERR | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
10:43:27.510 ERR |  ---> System.NullReferenceException: Object reference not set to an instance of an object.
10:43:27.510 ERR |    at FFXIVClientStructs.Interop.Resolver.ResolveFromCache() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 151
10:43:27.510 ERR |    at FFXIVClientStructs.Interop.Resolver.Resolve() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 171
10:43:27.510 ERR |    at visland.Plugin..ctor(DalamudPluginInterface dalamud) in /home/runner/work/ffxiv_visland/ffxiv_visland/ffxiv_visland/Plugin.cs:line 71
10:43:27.510 ERR |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
10:43:27.510 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
10:43:27.510 ERR |    --- End of inner exception stack trace ---
10:43:27.510 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
10:43:27.510 ERR |    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
10:43:27.510 ERR |    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 146
10:43:27.510 ERR |    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 454
10:43:27.510 ERR |    at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1580
10:43:27.510 ERR |    at Dalamud.Plugin.Internal.PluginManager.InstallPluginInternalAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Stream zipStream, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1416
10:43:27.510 ERR |    at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 810
10:43:32.939 VRB | Config saved
10:43:32.945 VRB | WindowSystem "DalamudCore" Window "Plugin Installer (TESTING)###XlPluginInstaller" lost focus
10:43:32.953 VRB | Config saved
10:43:33.535 DBG | [AutoRetainer] YesAlready locked
10:43:33.537 DBG | [AutoRetainer] FPS restrictions removed
10:43:33.537 DBG | [AutoRetainer] Setting FFXIV process priority to high.
```

</details>

<details><summary>This is my error trying to install if fresh, deleting the install manually and removing my config folder and files:</summary>

```
19:29:37.848 ERR | [LOCALPLUGIN] Error while loading V(ery) Island
19:29:37.848 ERR | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
19:29:37.848 ERR |  ---> System.NullReferenceException: Object reference not set to an instance of an object.
19:29:37.848 ERR |    at FFXIVClientStructs.Interop.Resolver.ResolveFromCache() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 151
19:29:37.848 ERR |    at FFXIVClientStructs.Interop.Resolver.Resolve() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 171
19:29:37.848 ERR |    at visland.Plugin..ctor(DalamudPluginInterface dalamud) in /home/runner/work/ffxiv_visland/ffxiv_visland/ffxiv_visland/Plugin.cs:line 71
19:29:37.848 ERR |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
19:29:37.848 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
19:29:37.848 ERR |    --- End of inner exception stack trace ---
19:29:37.848 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
19:29:37.848 ERR |    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
19:29:37.848 ERR |    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 146
19:29:37.848 ERR |    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 454
19:29:37.849 ERR | [PLUGINW] Plugin installer threw an unexpected error
19:29:37.849 ERR | System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
19:29:37.849 ERR |  ---> System.NullReferenceException: Object reference not set to an instance of an object.
19:29:37.849 ERR |    at FFXIVClientStructs.Interop.Resolver.ResolveFromCache() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 151
19:29:37.849 ERR |    at FFXIVClientStructs.Interop.Resolver.Resolve() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 171
19:29:37.849 ERR |    at visland.Plugin..ctor(DalamudPluginInterface dalamud) in /home/runner/work/ffxiv_visland/ffxiv_visland/ffxiv_visland/Plugin.cs:line 71
19:29:37.849 ERR |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
19:29:37.849 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
19:29:37.849 ERR |    --- End of inner exception stack trace ---
19:29:37.849 ERR |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
19:29:37.849 ERR |    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
19:29:37.849 ERR |    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 146
19:29:37.849 ERR |    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 454
19:29:37.849 ERR |    at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1580
19:29:37.849 ERR |    at Dalamud.Plugin.Internal.PluginManager.InstallPluginInternalAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Stream zipStream, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 1416
19:29:37.849 ERR |    at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason, Nullable`1 inheritedWorkingPluginId) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 810
```

</details>

**Comment by Jaksuhn** [comment]
switch your dalamud branch back to release. They broke the staging version
